#!/usr/bin/env python3
"""
Extract float32 weights from the ai85kws20netv3 QAT checkpoint and write
them as a C header file (kws20_32bit_weights.h) for the MAX78000 float32
CPU-only inference project.

Usage (run on cluster where PyTorch + ai8x-training is installed):
    cd ~/max78000/ai8x-training
    python3 <path_to_this_file>/extract_weights.py \
        --checkpoint ../ai8x-synthesis/trained/ai85-kws20_v3-qat8-q.pth.tar \
        --out        <path_to_kws20_32bit>/kws20_32bit_weights.h

The script loads the checkpoint, strips QAT quantization wrappers, and
exports the float32 weights and biases in the exact layout expected by
kws20_32bit_inference.c.
"""

import argparse
import sys
from pathlib import Path

import torch
import numpy as np


LAYER_MAP = [
    # (checkpoint_prefix,   var_prefix,   has_bias)
    ("voice_conv1",         "voice_conv1", False),
    ("voice_conv2",         "voice_conv2", False),
    ("voice_conv3",         "voice_conv3", False),
    ("voice_conv4",         "voice_conv4", False),
    ("kws_conv1",           "kws_conv1",   False),
    ("kws_conv2",           "kws_conv2",   False),
    ("kws_conv3",           "kws_conv3",   False),
    ("kws_conv4",           "kws_conv4",   False),
    ("fc",                  "fc",          False),
]

# Keys to try for the weight tensor in each layer's sub-module
WEIGHT_KEY_CANDIDATES = ["op.weight", "weight", "conv.weight", "linear.weight"]
BIAS_KEY_CANDIDATES   = ["op.bias",   "bias",   "conv.bias",   "linear.bias"]


def find_tensor(state, prefix, candidates):
    for cand in candidates:
        key = f"{prefix}.{cand}"
        if key in state:
            return state[key].float().detach().cpu().numpy()
    # Fallback: search for any key that starts with prefix and ends with the last part
    for cand in candidates:
        suffix = cand.split(".")[-1]
        for key in state:
            if key.startswith(prefix) and key.endswith(f".{suffix}"):
                return state[key].float().detach().cpu().numpy()
    return None


def to_c_array(name, arr, dtype="float"):
    flat = arr.flatten()
    lines = [f"static const {dtype} {name}[{len(flat)}] = {{"]
    per_row = 8
    for i in range(0, len(flat), per_row):
        chunk = flat[i:i+per_row]
        row = ", ".join(f"{v:.8e}f" for v in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", required=True, help=".pth.tar checkpoint file")
    ap.add_argument("--out", required=True, help="Output .h file path")
    args = ap.parse_args()

    ckpt_path = Path(args.checkpoint).expanduser().resolve()
    out_path  = Path(args.out).expanduser().resolve()

    print(f"Loading checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location="cpu")
    if "state_dict" in ckpt:
        state = ckpt["state_dict"]
    elif "model" in ckpt:
        state = ckpt["model"]
    else:
        state = ckpt

    # Remove 'module.' prefix if present (DataParallel)
    state = {k.replace("module.", ""): v for k, v in state.items()}

    print("State dict keys (first 30):")
    for k in list(state.keys())[:30]:
        print(f"  {k}")

    out_lines = [
        "/*",
        " * Auto-generated by extract_weights.py — do not edit.",
        f" * Source checkpoint: {ckpt_path.name}",
        " * Layout: (out_channels, in_channels, kernel_size) for conv weights",
        " *         (out_features, in_features) for fc weight",
        " */",
        "",
        "#ifndef KWS20_32BIT_WEIGHTS_H",
        "#define KWS20_32BIT_WEIGHTS_H",
        "",
    ]

    weight_info = []
    for layer_prefix, var_prefix, has_bias in LAYER_MAP:
        w = find_tensor(state, layer_prefix, WEIGHT_KEY_CANDIDATES)
        if w is None:
            print(f"WARNING: weight not found for {layer_prefix} — writing zeros placeholder")
            # Write a recognizable placeholder so compile succeeds
            out_lines += [
                f"/* PLACEHOLDER — {layer_prefix} weight not found in checkpoint */",
                f"static const float {var_prefix}_weight[1] = {{0.0f}};",
                f"static const float {var_prefix}_bias[1] = {{0.0f}};",
                "",
            ]
            continue

        print(f"  {layer_prefix}: weight shape {w.shape}")
        out_lines.append(f"/* {layer_prefix}: weight {list(w.shape)} */")
        out_lines.append(to_c_array(f"{var_prefix}_weight", w))
        weight_info.append((var_prefix, list(w.shape)))

        b = find_tensor(state, layer_prefix, BIAS_KEY_CANDIDATES)
        if b is not None:
            print(f"  {layer_prefix}: bias shape {b.shape}")
            out_lines.append(to_c_array(f"{var_prefix}_bias", b))
        else:
            n_out = w.shape[0]
            zero_bias = np.zeros(n_out, dtype=np.float32)
            out_lines.append(f"/* {layer_prefix}: no bias in checkpoint — using zeros */")
            out_lines.append(to_c_array(f"{var_prefix}_bias", zero_bias))

        out_lines.append("")

    out_lines += ["#endif /* KWS20_32BIT_WEIGHTS_H */", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines))
    print(f"\nWritten: {out_path}")
    print("\nWeight summary:")
    for name, shape in weight_info:
        total = 1
        for s in shape: total *= s
        print(f"  {name:20s} {str(shape):30s} {total*4/1024:.1f} KB")


if __name__ == "__main__":
    main()
