/*
 * Float32 software inference for ai85kws20netv3 on MAX78000 Cortex-M4F.
 *
 * Architecture (from ai85net-kws20-v3.py):
 *   voice_conv1 : Conv1d(128→100, k=1, pad=0) + ReLU
 *   voice_conv2 : Conv1d(100→96,  k=3, pad=0) + ReLU
 *   voice_conv3 : MaxPool1d(2) + Conv1d(96→64,  k=3, pad=1) + ReLU
 *   voice_conv4 : Conv1d(64→48,   k=3, pad=0) + ReLU
 *   kws_conv1   : MaxPool1d(2) + Conv1d(48→64,  k=3, pad=1) + ReLU
 *   kws_conv2   : Conv1d(64→96,   k=3, pad=0) + ReLU
 *   kws_conv3   : AvgPool1d(2) + Conv1d(96→100, k=3, pad=1) + ReLU
 *   kws_conv4   : MaxPool1d(2) + Conv1d(100→64, k=6, pad=1) + ReLU
 *   fc          : Linear(256→21)
 *
 * Tensor shapes (C, T):
 *   input        → (128, 128)
 *   voice_conv1  → (100, 128)
 *   voice_conv2  → ( 96, 126)
 *   voice_conv3  → ( 64,  63)
 *   voice_conv4  → ( 48,  61)
 *   kws_conv1    → ( 64,  30)
 *   kws_conv2    → ( 96,  28)
 *   kws_conv3    → (100,  14)
 *   kws_conv4    → ( 64,   4)
 *   flatten      → (256)
 *   fc           → ( 21)
 *
 * Weights are stored in kws20_32bit_weights.h (generated by extract_weights.py).
 */

#include "kws20_32bit_inference.h"
#include "kws20_32bit_weights.h"
#include <string.h>

/* ── Primitive operations ─────────────────────────────────────────────────── */

static inline float relu(float x) { return x > 0.0f ? x : 0.0f; }

/*
 * 1-D convolution: output[c_out, t] = sum_{c_in, k} w[c_out, c_in, k] * in[c_in, t+k] + bias
 * in       : (C_in,  T_in)  row-major
 * weights  : (C_out, C_in, K) row-major
 * bias     : (C_out,) or NULL
 * out      : (C_out, T_out) where T_out = T_in + 2*pad - K + 1
 */
static void conv1d_relu(
    const float *in,  int C_in,  int T_in,
    const float *w,   int C_out, int K, int pad,
    const float *bias,
    float *out)
{
    int T_out = T_in + 2 * pad - K + 1;
    for (int co = 0; co < C_out; ++co) {
        const float *wco = w + co * C_in * K;
        float b = bias ? bias[co] : 0.0f;
        for (int t = 0; t < T_out; ++t) {
            float acc = b;
            for (int ci = 0; ci < C_in; ++ci) {
                const float *wci = wco + ci * K;
                for (int k = 0; k < K; ++k) {
                    int t_in = t + k - pad;
                    if (t_in >= 0 && t_in < T_in)
                        acc += wci[k] * in[ci * T_in + t_in];
                }
            }
            out[co * T_out + t] = relu(acc);
        }
    }
}

/*
 * Max-pool 1-D, kernel=2, stride=2 (halves T).
 * in/out shape: (C, T_in) → (C, T_in/2)
 */
static void maxpool1d_k2(const float *in, int C, int T_in, float *out)
{
    int T_out = T_in / 2;
    for (int c = 0; c < C; ++c) {
        for (int t = 0; t < T_out; ++t) {
            float a = in[c * T_in + t * 2];
            float b = in[c * T_in + t * 2 + 1];
            out[c * T_out + t] = a > b ? a : b;
        }
    }
}

/*
 * Average-pool 1-D, kernel=2, stride=2 (halves T).
 */
static void avgpool1d_k2(const float *in, int C, int T_in, float *out)
{
    int T_out = T_in / 2;
    for (int c = 0; c < C; ++c) {
        for (int t = 0; t < T_out; ++t) {
            out[c * T_out + t] = 0.5f * (in[c * T_in + t * 2] + in[c * T_in + t * 2 + 1]);
        }
    }
}

/*
 * Fully-connected: out[n] = sum_m w[n,m] * in[m] + bias[n]
 */
static void linear(
    const float *in, int M,
    const float *w, int N,
    const float *bias,
    float *out)
{
    for (int n = 0; n < N; ++n) {
        float acc = bias ? bias[n] : 0.0f;
        const float *wn = w + n * M;
        for (int m = 0; m < M; ++m)
            acc += wn[m] * in[m];
        out[n] = acc;
    }
}

/* ── Scratch buffers (static to avoid stack overflow) ─────────────────────── */
/* Largest intermediate: voice_conv2 output = 96 * 126 = 12096 floats = 48 KB */
static float _buf_a[12096];  /* 96 * 126 — largest */
static float _buf_b[12096];
static float _buf_pool[12096];

/* ── Forward pass ─────────────────────────────────────────────────────────── */

int kws20_32bit_infer(const float *input, float *scores)
{
    /* voice_conv1: (128,128) → (100,128), k=1, pad=0 */
    conv1d_relu(input,    128, 128,
                voice_conv1_weight, 100, 1, 0,
                NULL,
                _buf_a);    /* _buf_a: (100,128) */

    /* voice_conv2: (100,128) → (96,126), k=3, pad=0 */
    conv1d_relu(_buf_a,   100, 128,
                voice_conv2_weight, 96, 3, 0,
                NULL,
                _buf_b);    /* _buf_b: (96,126) */

    /* voice_conv3: MaxPool(96,126)→(96,63), Conv→(64,63), k=3, pad=1 */
    maxpool1d_k2(_buf_b, 96, 126, _buf_pool);   /* _buf_pool: (96,63) */
    conv1d_relu(_buf_pool, 96, 63,
                voice_conv3_weight, 64, 3, 1,
                NULL,
                _buf_a);    /* _buf_a: (64,63) */

    /* voice_conv4: (64,63) → (48,61), k=3, pad=0 */
    conv1d_relu(_buf_a,   64, 63,
                voice_conv4_weight, 48, 3, 0,
                NULL,
                _buf_b);    /* _buf_b: (48,61) */

    /* kws_conv1: MaxPool(48,61)→(48,30), Conv→(64,30), k=3, pad=1 */
    maxpool1d_k2(_buf_b, 48, 61, _buf_pool);    /* _buf_pool: (48,30) — floor(61/2)=30 */
    conv1d_relu(_buf_pool, 48, 30,
                kws_conv1_weight, 64, 3, 1,
                NULL,
                _buf_a);    /* _buf_a: (64,30) */

    /* kws_conv2: (64,30) → (96,28), k=3, pad=0 */
    conv1d_relu(_buf_a,   64, 30,
                kws_conv2_weight, 96, 3, 0,
                NULL,
                _buf_b);    /* _buf_b: (96,28) */

    /* kws_conv3: AvgPool(96,28)→(96,14), Conv→(100,14), k=3, pad=1 */
    avgpool1d_k2(_buf_b, 96, 28, _buf_pool);    /* _buf_pool: (96,14) */
    conv1d_relu(_buf_pool, 96, 14,
                kws_conv3_weight, 100, 3, 1,
                NULL,
                _buf_a);    /* _buf_a: (100,14) */

    /* kws_conv4: MaxPool(100,14)→(100,7), Conv→(64,4), k=6, pad=1 */
    maxpool1d_k2(_buf_a, 100, 14, _buf_pool);   /* _buf_pool: (100,7) */
    conv1d_relu(_buf_pool, 100, 7,
                kws_conv4_weight, 64, 6, 1,
                NULL,
                _buf_b);    /* _buf_b: (64,4) = 256 floats */

    /* fc: flatten(64,4)=256 → 21 */
    linear(_buf_b, 256, fc_weight, 21, NULL, scores);

    return KWS32_OK;
}

int kws20_32bit_argmax(const float *scores, int n)
{
    int best = 0;
    for (int i = 1; i < n; ++i)
        if (scores[i] > scores[best])
            best = i;
    return best;
}
