/*
 * Host-side MFCC validation test.
 *
 * Compiles and runs on Linux (no GAP9 needed).
 * Reads test audio from test_vectors.h (generated by generate_mfcc_tables.py),
 * computes MFCC with the C implementation, compares against Python reference.
 *
 * Build (from mfcc/tests/):
 *   gcc -O2 -I../include -o test_mfcc_host test_mfcc_host.c \
 *       ../src/mfcc.c ../src/mfcc_tables.c -lm
 * Run:
 *   ./test_mfcc_host
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "mfcc.h"
#include "test_vectors.h"

/* ── Test infrastructure ─────────────────────────────────────────────────── */

static int   g_tests_run    = 0;
static int   g_tests_passed = 0;

static float absf(float x) { return x < 0.0f ? -x : x; }

typedef struct {
    float max_abs;
    float mean_abs;
    float rms;
    int   n_outliers;   /* |err| > threshold */
} ErrorStats;

static ErrorStats compute_error(const float *got, const float *ref, int n,
                                float threshold)
{
    ErrorStats s = {0};
    double sum_abs = 0.0, sum_sq = 0.0;
    for (int i = 0; i < n; i++) {
        float e = absf(got[i] - ref[i]);
        if (e > s.max_abs) s.max_abs = e;
        sum_abs += e;
        sum_sq  += (double)e * e;
        if (e > threshold) s.n_outliers++;
    }
    s.mean_abs = (float)(sum_abs / n);
    s.rms      = (float)sqrt(sum_sq / n);
    return s;
}

#define RUN_TEST(name, audio, ref_mfcc) \
    run_test(#name, audio, TEST_AUDIO_LEN, ref_mfcc, MFCC_OUTPUT_SIZE)

static void run_test(const char *name, const float *audio, int audio_len,
                     const float *ref, int out_len)
{
    (void)audio_len;
    g_tests_run++;

    float output[MFCC_OUTPUT_SIZE];
    mfcc_compute(audio, output);

    /* Tolerance: 1e-3 absolute (numerical differences from float vs double FFT,
       trig approximations). Max tolerable for a 10-coeff MFCC is ~0.01.       */
    float threshold = 1e-3f;
    ErrorStats err  = compute_error(output, ref, out_len, threshold);

    int passed = (err.max_abs < 1e-2f) && (err.n_outliers == 0 ||
                  (float)err.n_outliers / out_len < 0.01f);

    printf("  %-20s  max_abs=%.3e  mean_abs=%.3e  rms=%.3e  outliers=%d/%d  %s\n",
           name, err.max_abs, err.mean_abs, err.rms, err.n_outliers, out_len,
           passed ? "PASS" : "FAIL");

    if (!passed) {
        /* Print first few bad elements for debugging */
        int shown = 0;
        for (int i = 0; i < out_len && shown < 5; i++) {
            float e = absf(output[i] - ref[i]);
            if (e > threshold) {
                int frame = i / MFCC_N_MFCC;
                int coeff = i % MFCC_N_MFCC;
                printf("    [frame=%d coeff=%d]  got=%.6f  ref=%.6f  err=%.3e\n",
                       frame, coeff, output[i], ref[i], e);
                shown++;
            }
        }
    } else {
        g_tests_passed++;
    }
}

/* ── Sanity check: silence gives constant log(eps) after mel+log ────────── */
static void test_silence_sanity(void)
{
    g_tests_run++;
    float silence[MFCC_AUDIO_LEN];
    memset(silence, 0, sizeof(silence));
    float output[MFCC_OUTPUT_SIZE];
    mfcc_compute(silence, output);

    /* All frames should be identical for silence */
    int ok = 1;
    for (int t = 1; t < MFCC_N_FRAMES && ok; t++) {
        for (int c = 0; c < MFCC_N_MFCC && ok; c++) {
            float diff = absf(output[t * MFCC_N_MFCC + c] -
                              output[0 * MFCC_N_MFCC + c]);
            if (diff > 1e-5f) ok = 0;
        }
    }
    printf("  %-20s  all_frames_identical=%s  %s\n",
           "silence_sanity", ok ? "yes" : "no", ok ? "PASS" : "FAIL");
    if (ok) g_tests_passed++;
}

/* ── Test int16 path gives same result as float path ───────────────────── */
static void test_int16_path(void)
{
    g_tests_run++;
    /* Convert sine_1k to int16 and back — small quantisation error expected */
    int16_t audio_i16[MFCC_AUDIO_LEN];
    float   audio_ref_f32[MFCC_AUDIO_LEN];
    for (int i = 0; i < MFCC_AUDIO_LEN; i++) {
        int16_t s = (int16_t)(test_audio_sine_1k[i] * 32767.0f);
        audio_i16[i]      = s;
        audio_ref_f32[i]  = (float)s / 32768.0f;
    }
    float out_i16[MFCC_OUTPUT_SIZE];
    float out_f32[MFCC_OUTPUT_SIZE];
    mfcc_compute_int16(audio_i16, out_i16);
    mfcc_compute(audio_ref_f32, out_f32);

    ErrorStats err = compute_error(out_i16, out_f32, MFCC_OUTPUT_SIZE, 1e-4f);
    int passed = (err.max_abs < 1e-3f);
    printf("  %-20s  max_abs=%.3e  %s\n",
           "int16_path", err.max_abs, passed ? "PASS" : "FAIL");
    if (passed) g_tests_passed++;
}

/* ── Verify output shape is correct ─────────────────────────────────────── */
static void test_output_shape(void)
{
    g_tests_run++;
    float output[MFCC_OUTPUT_SIZE];
    mfcc_compute(test_audio_white_noise, output);

    /* Check that N_FRAMES × N_MFCC = 490 and layout is frame-major */
    int ok = (MFCC_N_FRAMES == 49) && (MFCC_N_MFCC == 10) &&
             (MFCC_OUTPUT_SIZE == 490);
    printf("  %-20s  frames=%d  coeffs=%d  total=%d  %s\n",
           "output_shape", MFCC_N_FRAMES, MFCC_N_MFCC, MFCC_OUTPUT_SIZE,
           ok ? "PASS" : "FAIL");
    if (ok) g_tests_passed++;
}

/* ── main ────────────────────────────────────────────────────────────────── */
int main(void)
{
    printf("=== MFCC Host Validation Tests ===\n\n");

    printf("Test vectors from Python reference:\n");
    RUN_TEST(silence,     test_audio_silence,     test_mfcc_ref_silence);
    RUN_TEST(sine_1k,     test_audio_sine_1k,     test_mfcc_ref_sine_1k);
    RUN_TEST(white_noise, test_audio_white_noise,  test_mfcc_ref_white_noise);

    printf("\nSanity checks:\n");
    test_silence_sanity();
    test_int16_path();
    test_output_shape();

    printf("\n=== Results: %d/%d passed ===\n", g_tests_passed, g_tests_run);
    return (g_tests_passed == g_tests_run) ? 0 : 1;
}
